import { ExecArgs } from "@medusajs/framework/types"
import { ContainerRegistrationKeys } from "@medusajs/framework/utils"
import { createShippingOptionsWorkflow } from "@medusajs/core-flows"
import type { Knex } from "knex"

import fs from "node:fs/promises"
import path from "node:path"

import * as yaml from "js-yaml"

import { validatePrerequisites } from "./gp-config-sync-catalog"
import { listRegionsWithCountries, selectRegionForMarket } from "./gp-config-sync-payments"
import { parseDryRunFlag } from "./gp-sync-dry-run"

const MANUAL_PROVIDER_ID = "manual_manual"
const OPTION_TYPE_CODE = "gp-checkout"
const OPTION_TYPE_LABEL = "GP Checkout"
const OPTION_TYPE_DESCRIPTION = "Autogenerated storefront checkout shipping option"

type ParsedArgs = {
  instanceId: string
  marketId: string
  configRoot: string
  dryRun: boolean
}

type MarketRuntimeConfig = {
  currency?: string
  countries?: string[]
}

type ShippingProfileRow = {
  shipping_profile_id: string
}

type ServiceZoneRow = {
  service_zone_id: string
  stock_location_id: string
  stock_location_name: string | null
}

type SellerStockLocationRow = {
  stock_location_id: string
}

type SellerZoneRow = {
  seller_id: string
  service_zone_id: string
}

type MarketSellerRow = {
  seller_id: string
  seller_name: string
  seller_handle: string
}

type ExistingShippingOptionRow = {
  id: string
  service_zone_id: string
  shipping_profile_id: string
}

type SellerShippingOptionLinkRow = {
  id: string
  seller_id: string
}

function resolveService(container: any, keysToTry: string[]): any {
  for (const key of keysToTry) {
    try {
      return container.resolve(key)
    } catch {
      // keep trying aliases
    }
  }

  throw new Error(`Unable to resolve service. Tried: ${keysToTry.join(", ")}`)
}

export function parseArgs(args: string[] | undefined): ParsedArgs {
  const instanceId = (args?.[0] ?? process.env.GP_INSTANCE_ID ?? "gp-dev").trim()
  const marketId = (args?.[1] ?? process.env.GP_MARKET_ID ?? "bonbeauty").trim()
  const configRoot = (
    process.env.GP_CONFIG_ROOT ?? path.resolve(process.cwd(), "../config")
  ).trim()
  const dryRun = parseDryRunFlag(args)

  if (!instanceId) throw new Error("instanceId is required (args[0] or GP_INSTANCE_ID)")
  if (!marketId) throw new Error("marketId is required (args[1] or GP_MARKET_ID)")
  if (!configRoot) throw new Error("configRoot is required (GP_CONFIG_ROOT)")

  return { instanceId, marketId, configRoot, dryRun }
}

async function readYamlFile<T>(filePath: string): Promise<T> {
  const raw = await fs.readFile(filePath, "utf8")
  const doc = yaml.load(raw, { schema: yaml.JSON_SCHEMA })

  if (!doc || typeof doc !== "object") {
    throw new Error(`Invalid YAML document: ${filePath}`)
  }

  return doc as T
}

async function loadMarketRuntimeConfig(args: ParsedArgs): Promise<MarketRuntimeConfig> {
  const marketPath = path.resolve(
    args.configRoot,
    args.instanceId,
    "markets",
    args.marketId,
    "market.yaml"
  )

  return readYamlFile<MarketRuntimeConfig>(marketPath)
}

function extractRows<T>(result: any): T[] {
  if (Array.isArray(result?.rows)) return result.rows as T[]
  if (Array.isArray(result)) return result as T[]
  return []
}

function buildSyntheticId(prefix: string): string {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`
}

function normalizeComparableName(value: string | null | undefined): string {
  return (value ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "")
}

async function listMarketShippingProfiles(db: Knex, marketId: string): Promise<string[]> {
  const result = await db.raw(
    `
      SELECT DISTINCT psp.shipping_profile_id
      FROM product p
      INNER JOIN product_shipping_profile psp
        ON psp.product_id = p.id
      WHERE p.deleted_at IS NULL
        AND p.metadata->'gp'->>'market_id' = ?
      ORDER BY psp.shipping_profile_id ASC
    `,
    [marketId]
  )

  return extractRows<ShippingProfileRow>(result)
    .map(row => row.shipping_profile_id)
    .filter(Boolean)
}

async function listMarketSellers(db: Knex, marketId: string): Promise<MarketSellerRow[]> {
  const result = await db.raw(
    `
      SELECT DISTINCT
        sspp.seller_id,
        s.name AS seller_name,
        s.handle AS seller_handle
      FROM product p
      INNER JOIN seller_seller_product_product sspp
        ON sspp.product_id = p.id
       AND sspp.deleted_at IS NULL
      INNER JOIN seller s
        ON s.id = sspp.seller_id
       AND s.deleted_at IS NULL
      WHERE p.deleted_at IS NULL
        AND p.metadata->'gp'->>'market_id' = ?
        AND s.store_status = 'ACTIVE'
      ORDER BY s.name ASC
    `,
    [marketId]
  )

  return extractRows<MarketSellerRow>(result)
}

async function listServiceZoneBackedStockLocations(db: Knex): Promise<ServiceZoneRow[]> {
  const result = await db.raw(
    `
      SELECT DISTINCT
        sz.id AS service_zone_id,
        lfs.stock_location_id,
        sl.name AS stock_location_name
      FROM location_fulfillment_set lfs
      INNER JOIN stock_location sl
        ON sl.id = lfs.stock_location_id
       AND sl.deleted_at IS NULL
      INNER JOIN service_zone sz
        ON sz.fulfillment_set_id = lfs.fulfillment_set_id
       AND sz.deleted_at IS NULL
      WHERE lfs.deleted_at IS NULL
      ORDER BY sl.name ASC, sz.id ASC
    `
  )

  return extractRows<ServiceZoneRow>(result)
}

async function listMarketServiceZones(db: Knex, salesChannelId: string): Promise<ServiceZoneRow[]> {
  const result = await db.raw(
    `
      SELECT DISTINCT
        sz.id AS service_zone_id,
        scl.stock_location_id,
        sl.name AS stock_location_name
      FROM sales_channel sc
      INNER JOIN sales_channel_stock_location scl
        ON scl.sales_channel_id = sc.id
       AND scl.deleted_at IS NULL
      INNER JOIN stock_location sl
        ON sl.id = scl.stock_location_id
       AND sl.deleted_at IS NULL
      INNER JOIN location_fulfillment_set lfs
        ON lfs.stock_location_id = sl.id
       AND lfs.deleted_at IS NULL
      INNER JOIN service_zone sz
        ON sz.fulfillment_set_id = lfs.fulfillment_set_id
       AND sz.deleted_at IS NULL
      WHERE sc.deleted_at IS NULL
        AND sc.id = ?
      ORDER BY sl.name ASC, sz.id ASC
    `,
    [salesChannelId]
  )

  return extractRows<ServiceZoneRow>(result)
}

async function listSellerIdsByServiceZone(
  db: Knex,
  serviceZoneIds: string[]
): Promise<Map<string, string[]>> {
  if (serviceZoneIds.length === 0) {
    return new Map()
  }

  const result = await db.raw(
    `
      SELECT seller_id, service_zone_id
      FROM seller_seller_fulfillment_service_zone
      WHERE deleted_at IS NULL
        AND service_zone_id = ANY(?::text[])
      ORDER BY service_zone_id ASC, seller_id ASC
    `,
    [serviceZoneIds]
  )

  const map = new Map<string, string[]>()
  for (const row of extractRows<SellerZoneRow>(result)) {
    const existing = map.get(row.service_zone_id) ?? []
    existing.push(row.seller_id)
    map.set(row.service_zone_id, existing)
  }

  return map
}

async function listExistingShippingOptions(
  db: Knex,
  shippingProfileIds: string[],
  serviceZoneIds: string[]
): Promise<Map<string, ExistingShippingOptionRow>> {
  if (shippingProfileIds.length === 0 || serviceZoneIds.length === 0) {
    return new Map()
  }

  const result = await db.raw(
    `
      SELECT id, service_zone_id, shipping_profile_id
      FROM shipping_option
      WHERE deleted_at IS NULL
        AND provider_id = ?
        AND shipping_profile_id = ANY(?::text[])
        AND service_zone_id = ANY(?::text[])
      ORDER BY created_at ASC
    `,
    [MANUAL_PROVIDER_ID, shippingProfileIds, serviceZoneIds]
  )

  return new Map(
    extractRows<ExistingShippingOptionRow>(result).map(row => [
      `${row.shipping_profile_id}::${row.service_zone_id}`,
      row,
    ])
  )
}

async function ensureLocationProviderLink(
  db: Knex,
  stockLocationId: string,
  dryRun: boolean
): Promise<"created" | "existing"> {
  const existing = await db("location_fulfillment_provider")
    .select("stock_location_id")
    .where({
      stock_location_id: stockLocationId,
      fulfillment_provider_id: MANUAL_PROVIDER_ID,
    })
    .whereNull("deleted_at")
    .first()

  if (existing) {
    return "existing"
  }

  if (dryRun) {
    return "created"
  }

  await db("location_fulfillment_provider").insert({
    stock_location_id: stockLocationId,
    fulfillment_provider_id: MANUAL_PROVIDER_ID,
    id: buildSyntheticId("locfp"),
  })

  return "created"
}

async function ensureSalesChannelStockLocationLink(
  db: Knex,
  salesChannelId: string,
  stockLocationId: string,
  dryRun: boolean
): Promise<"created" | "existing"> {
  const existing = await db("sales_channel_stock_location")
    .select("sales_channel_id")
    .where({
      sales_channel_id: salesChannelId,
      stock_location_id: stockLocationId,
    })
    .whereNull("deleted_at")
    .first()

  if (existing) {
    return "existing"
  }

  if (dryRun) {
    return "created"
  }

  await db("sales_channel_stock_location").insert({
    sales_channel_id: salesChannelId,
    stock_location_id: stockLocationId,
    id: buildSyntheticId("scloc"),
  })

  return "created"
}

async function ensureSellerShippingOptionLink(
  db: Knex,
  sellerId: string,
  shippingOptionId: string,
  dryRun: boolean
): Promise<"created" | "existing"> {
  const existing = await db("seller_seller_fulfillment_shipping_option")
    .select("seller_id")
    .where({ seller_id: sellerId, shipping_option_id: shippingOptionId })
    .whereNull("deleted_at")
    .first()

  if (existing) {
    return "existing"
  }

  if (dryRun) {
    return "created"
  }

  await db("seller_seller_fulfillment_shipping_option").insert({
    seller_id: sellerId,
    shipping_option_id: shippingOptionId,
    id: buildSyntheticId("ssfsso"),
  })

  return "created"
}

async function pruneSellerShippingOptionLinks(
  db: Knex,
  shippingOptionId: string,
  allowedSellerIds: string[],
  dryRun: boolean
): Promise<number> {
  const existing = await db("seller_seller_fulfillment_shipping_option")
    .select("id", "seller_id")
    .where({ shipping_option_id: shippingOptionId })
    .whereNull("deleted_at")

  const allowedSellerIdSet = new Set(allowedSellerIds)
  const staleLinks = (existing as SellerShippingOptionLinkRow[]).filter(
    row => !allowedSellerIdSet.has(row.seller_id)
  )

  if (staleLinks.length === 0) {
    return 0
  }

  if (dryRun) {
    return staleLinks.length
  }

  await db("seller_seller_fulfillment_shipping_option")
    .whereIn(
      "id",
      staleLinks.map(row => row.id)
    )
    .update({ deleted_at: db.fn.now() })

  return staleLinks.length
}

async function resolveShippingOptionTypeId(db: Knex, fulfillmentService: any, dryRun: boolean) {
  const existing = await db("shipping_option_type")
    .select("id")
    .where({ code: OPTION_TYPE_CODE })
    .whereNull("deleted_at")
    .first<{ id: string }>()

  if (existing?.id) {
    return { id: existing.id, created: false }
  }

  if (dryRun) {
    return { id: `dryrun-${OPTION_TYPE_CODE}`, created: true }
  }

  const created = await fulfillmentService.createShippingOptionTypes({
    label: OPTION_TYPE_LABEL,
    code: OPTION_TYPE_CODE,
    description: OPTION_TYPE_DESCRIPTION,
  })

  return { id: created.id as string, created: true }
}

export default async function gpConfigSyncShipping({ container, args }: ExecArgs) {
  const parsedArgs = parseArgs(args)
  const marketConfig = await loadMarketRuntimeConfig(parsedArgs)
  const db = container.resolve(ContainerRegistrationKeys.PG_CONNECTION) as Knex
  const fulfillmentService = resolveService(container, [
    "fulfillment",
    "fulfillmentModuleService",
    "IFulfillmentModuleService",
    "fulfillment_module",
  ])

  const currency = (marketConfig.currency ?? "").trim()
  const countries = Array.isArray(marketConfig.countries) ? marketConfig.countries : []
  if (!currency) {
    throw new Error("market.currency is required to bootstrap shipping options")
  }

  const prereqs = await validatePrerequisites(container, parsedArgs.marketId, currency, [])

  const [marketSellers, serviceZoneBackedStockLocations] = await Promise.all([
    listMarketSellers(db, parsedArgs.marketId),
    listServiceZoneBackedStockLocations(db),
  ])
  const activeMarketSellerIds = new Set(marketSellers.map(seller => seller.seller_id))

  const matchedSellerIdsByServiceZone = new Map<string, string[]>()
  const matchedStockLocationIds = new Set<string>()

  for (const seller of marketSellers) {
    const sellerKeys = [
      normalizeComparableName(seller.seller_name),
      normalizeComparableName(seller.seller_handle),
    ].filter(Boolean)

    for (const location of serviceZoneBackedStockLocations) {
      const normalizedLocationName = normalizeComparableName(location.stock_location_name)
      if (!normalizedLocationName || !sellerKeys.includes(normalizedLocationName)) {
        continue
      }

      matchedStockLocationIds.add(location.stock_location_id)
      const existing = matchedSellerIdsByServiceZone.get(location.service_zone_id) ?? []
      if (!existing.includes(seller.seller_id)) {
        existing.push(seller.seller_id)
        matchedSellerIdsByServiceZone.set(location.service_zone_id, existing)
      }
    }
  }

  let createdSalesChannelLinks = 0
  for (const stockLocationId of matchedStockLocationIds) {
    const linkStatus = await ensureSalesChannelStockLocationLink(
      db,
      prereqs.salesChannelId,
      stockLocationId,
      parsedArgs.dryRun
    )

    if (linkStatus === "created") {
      createdSalesChannelLinks += 1
    }
  }

  const [regions, shippingProfileIds, serviceZones] = await Promise.all([
    listRegionsWithCountries(db),
    listMarketShippingProfiles(db, parsedArgs.marketId),
    listMarketServiceZones(db, prereqs.salesChannelId),
  ])

  const region = selectRegionForMarket(regions, currency, countries)

  if (shippingProfileIds.length === 0) {
    console.warn(`No shipping profiles found for market '${parsedArgs.marketId}'. Skipping shipping sync.`)
    return
  }

  if (serviceZones.length === 0) {
    console.warn(`No service zones found for market '${parsedArgs.marketId}'. Skipping shipping sync.`)
    return
  }

  const { id: shippingOptionTypeId, created: createdType } = await resolveShippingOptionTypeId(
    db,
    fulfillmentService,
    parsedArgs.dryRun
  )

  const sellerIdsByServiceZone = await listSellerIdsByServiceZone(
    db,
    serviceZones.map(zone => zone.service_zone_id)
  )

  for (const [serviceZoneId, sellerIds] of sellerIdsByServiceZone.entries()) {
    sellerIdsByServiceZone.set(
      serviceZoneId,
      sellerIds.filter(sellerId => activeMarketSellerIds.has(sellerId))
    )
  }

  for (const [serviceZoneId, sellerIds] of matchedSellerIdsByServiceZone.entries()) {
    const existing = sellerIdsByServiceZone.get(serviceZoneId) ?? []
    for (const sellerId of sellerIds) {
      if (activeMarketSellerIds.has(sellerId) && !existing.includes(sellerId)) {
        existing.push(sellerId)
      }
    }
    sellerIdsByServiceZone.set(serviceZoneId, existing)
  }
  const existingOptions = await listExistingShippingOptions(
    db,
    shippingProfileIds,
    serviceZones.map(zone => zone.service_zone_id)
  )

  let createdOptions = 0
  let reusedOptions = 0
  let createdLocationLinks = 0
  let createdSellerLinks = 0
  let prunedSellerLinks = 0

  for (const zone of serviceZones) {
    const locationLinkStatus = await ensureLocationProviderLink(
      db,
      zone.stock_location_id,
      parsedArgs.dryRun
    )
    if (locationLinkStatus === "created") {
      createdLocationLinks += 1
    }

    for (const shippingProfileId of shippingProfileIds) {
      const key = `${shippingProfileId}::${zone.service_zone_id}`
      let shippingOptionId = existingOptions.get(key)?.id ?? null

      if (!shippingOptionId) {
        if (parsedArgs.dryRun) {
          shippingOptionId = `dryrun-${shippingProfileId}-${zone.service_zone_id}`
        } else {
          const { result } = await createShippingOptionsWorkflow(container).run({
            input: [
              {
                name: `${parsedArgs.marketId} checkout`,
                price_type: "flat",
                service_zone_id: zone.service_zone_id,
                shipping_profile_id: shippingProfileId,
                provider_id: MANUAL_PROVIDER_ID,
                type: shippingOptionTypeId,
                prices: [
                  {
                    region_id: region.id,
                    amount: 0,
                  },
                ],
                rules: [
                  {
                    attribute: "enabled_in_store",
                    operator: "eq",
                    value: "true",
                  },
                  {
                    attribute: "is_return",
                    operator: "eq",
                    value: "false",
                  },
                ],
                data: {
                  gp_market_id: parsedArgs.marketId,
                },
                metadata: {
                  gp: {
                    market_id: parsedArgs.marketId,
                    autogenerated: true,
                    source: "gp-config-sync-shipping",
                  },
                },
              },
            ],
          })

          shippingOptionId = result[0]?.id as string
        }

        createdOptions += 1
      } else {
        reusedOptions += 1
      }

      const allowedSellerIds = sellerIdsByServiceZone.get(zone.service_zone_id) ?? []

      for (const sellerId of allowedSellerIds) {
        const sellerLinkStatus = await ensureSellerShippingOptionLink(
          db,
          sellerId,
          shippingOptionId,
          parsedArgs.dryRun
        )

        if (sellerLinkStatus === "created") {
          createdSellerLinks += 1
        }
      }

      prunedSellerLinks += await pruneSellerShippingOptionLinks(
        db,
        shippingOptionId,
        allowedSellerIds,
        parsedArgs.dryRun
      )
    }
  }

  console.log(
    JSON.stringify(
      {
        ok: true,
        dry_run: parsedArgs.dryRun,
        instance_id: parsedArgs.instanceId,
        market_id: parsedArgs.marketId,
        shipping_option_type_created: createdType,
        created_options: createdOptions,
        reused_options: reusedOptions,
        created_sales_channel_stock_location_links: createdSalesChannelLinks,
        created_location_provider_links: createdLocationLinks,
        created_seller_shipping_links: createdSellerLinks,
        pruned_seller_shipping_links: prunedSellerLinks,
      },
      null,
      2
    )
  )
}