import { Migration } from "@medusajs/framework/mikro-orm/migrations";

/**
 * Index for correlated subquery in filterProductIdsByFilters() min_rating filter.
 *
 * seller_seller_review_review is auto-generated by Medusa link (@mercurjs/reviews).
 * The junction table has no index on seller_id — our correlated subquery needs it
 * to avoid sequential scan per seller row.
 *
 * Partial index (WHERE deleted_at IS NULL) matches the subquery's filter clause.
 */
export class Migration20260312100000 extends Migration {
  async up(): Promise<void> {
    this.addSql(
      `CREATE INDEX IF NOT EXISTS idx_ssrr_seller_id ON seller_seller_review_review (seller_id) WHERE deleted_at IS NULL`
    );
  }

  async down(): Promise<void> {
    this.addSql(`DROP INDEX IF EXISTS idx_ssrr_seller_id`);
  }
}
