/**
 * Story v160-cleanup-41: JCA PDF renderer — real pdfkit-backed Buffer.
 *
 * Replaces the text-Buffer placeholder from Story 7.5 (TF-100 deferred) with
 * a real PDF binary generated by pdfkit (in-process, no Chromium dependency).
 *
 * Design decisions (cleanup-41 OQ resolutions):
 *   OQ #1 — pdfkit chosen (lekkie, in-process, ~250KB bundle vs Chromium ~300MB)
 *   OQ #2 — Opcja B: legacy .txt artefacts retain format=text-legacy metadata;
 *            new generation always produces .pdf; v1.7.0 retire plan in backlog
 *   OQ #4 — PDF metadata set: Title, Author, Subject, Keywords (terms excerpt)
 *   OQ #5 — Helvetica used (ASCII-safe legal text); if PL chars required in
 *            future, embed DejaVuSans.ttf in lib/fonts/ (deferred to v1.7.0)
 *
 * BACKWARDS COMPAT NOTE (AC6 Opcja B):
 *   Legacy .txt artefacts stored by Story 7.5 carry format=text-legacy in any
 *   event_store payload. New generation always writes .pdf. Migration script
 *   deferred to v1.7.0 — see specs/proposed/v1.7.0/cleanup-deferred-from-v160.md.
 */

import PDFDocument from "pdfkit"

export interface RenderJcaPdfOptions {
  /** Vendor display name — appears in PDF title + body */
  vendorName: string
  /** Full JCA terms text (pre-hydrated from template) */
  terms: string
  /** JCA unique identifier */
  jcaId: string
  /** ISO date string for generation timestamp */
  generatedAt: string
}

/**
 * Renders a JCA (Joint Controllership Agreement) as a real PDF Buffer.
 *
 * Returns a Promise<Buffer> whose first 5 bytes are the magic bytes `%PDF-`.
 * Buffer length is always > 1 KB for any non-empty vendorName/terms input.
 *
 * Signature changed from sync (Buffer) to async (Promise<Buffer>) because
 * pdfkit uses a streaming model — collect chunks via "data" events, resolve
 * on "end". All callers (route.ts) must await the result.
 */
export async function renderJcaPdf({
  vendorName,
  terms,
  jcaId,
  generatedAt,
}: RenderJcaPdfOptions): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({
      info: {
        Title: `JCA-${vendorName}`,
        Author: "Grow Platform",
        Subject: "Joint Controllership Agreement",
        Creator: "Grow Platform v1.6.0",
        // First 100 chars of terms embedded as Keywords for searchability
        // and verifiability (Info dict is stored uncompressed in PDF binary).
        Keywords: terms.substring(0, 100),
      },
      margins: { top: 72, bottom: 72, left: 72, right: 72 },
    })

    const chunks: Buffer[] = []
    doc.on("data", (chunk: Buffer) => chunks.push(chunk))
    doc.on("end", () => resolve(Buffer.concat(chunks)))
    doc.on("error", reject)

    // ── Title ──────────────────────────────────────────────────────────────
    doc
      .fontSize(18)
      .font("Helvetica-Bold")
      .text("JOINT CONTROLLERSHIP AGREEMENT", { align: "center" })

    doc.moveDown(0.5)
    doc
      .fontSize(11)
      .font("Helvetica")
      .text(`JCA ID: ${jcaId}`, { align: "center" })
      .text(`Generated: ${generatedAt}`, { align: "center" })

    doc.moveDown(1)

    // ── Vendor block ───────────────────────────────────────────────────────
    doc.fontSize(13).font("Helvetica-Bold").text("Vendor / Data Processor")
    doc.moveDown(0.3)
    doc.fontSize(11).font("Helvetica").text(`Name: ${vendorName}`)

    doc.moveDown(1)

    // ── Terms body ─────────────────────────────────────────────────────────
    doc.fontSize(13).font("Helvetica-Bold").text("Terms and Conditions")
    doc.moveDown(0.5)
    doc
      .fontSize(10)
      .font("Helvetica")
      .text(terms, { align: "justify", lineGap: 2 })

    doc.moveDown(2)

    // ── Signature block ────────────────────────────────────────────────────
    doc.fontSize(11).font("Helvetica-Bold").text("Signatures")
    doc.moveDown(0.5)
    doc
      .font("Helvetica")
      .fontSize(10)
      .text(
        "Controller representative: ______________________________   Date: ____________",
      )
    doc.moveDown(0.5)
    doc.text(
      "Vendor representative:      ______________________________   Date: ____________",
    )

    doc.end()
  })
}

/**
 * Returns the file extension for the rendered output.
 * v1.6.0+: always ".pdf"
 *
 * @deprecated Legacy .txt artefacts from Story 7.5 carry extension ".txt" —
 * those are marked format=text-legacy. New generation always uses ".pdf".
 * Retire plan: v1.7.0 migration script (specs/proposed/v1.7.0/cleanup-deferred).
 */
export function getRendererExtension(): string {
  return ".pdf"
}

/**
 * Returns the MIME type for the rendered output.
 * v1.6.0+: always "application/pdf"
 */
export function getRendererMimeType(): string {
  return "application/pdf"
}

/**
 * @deprecated renderPDF was the Story 7.5 text-Buffer stub. Use renderJcaPdf().
 * Kept for backwards compat during v1.6.0 transition; will be removed in v1.7.0.
 * Legacy artefacts written by renderPDF have format=text-legacy in metadata.
 */
export function renderPDF(hydratedMarkdown: string): Buffer {
  // LEGACY STUB — returns text Buffer (format=text-legacy).
  // Do NOT use for new JCA generation. See renderJcaPdf() above.
  return Buffer.from(hydratedMarkdown, "utf-8")
}
