/**
 * Story v160-cleanup-41: JCA PDF renderer — real pdfkit-backed Buffer.
 *
 * Replaces the text-Buffer placeholder from Story 7.5 (TF-100 deferred) with
 * a real PDF binary generated by pdfkit (in-process, no Chromium dependency).
 *
 * Review fixes applied (post-adversarial):
 *   B-2 — terms NO LONGER embedded in PDF Info.Keywords (PII leakage)
 *   B-4 — DejaVuSans Unicode TTF registered for Polish chars (ąćęłńóśźż)
 *   B-5 — vendorName sanitized (control chars stripped, length-bounded)
 *   B-8 — legacy renderPDF() removed (no callers; dead code)
 */

import path from "node:path"
import fs from "node:fs"
import PDFDocument from "pdfkit"

export interface RenderJcaPdfOptions {
  /** Vendor display name — appears in PDF title + body */
  vendorName: string
  /** Full JCA terms text (pre-hydrated from template) */
  terms: string
  /** JCA unique identifier */
  jcaId: string
  /** ISO date string for generation timestamp */
  generatedAt: string
}

const FONTS_DIR = path.join(__dirname, "fonts")
const DEJAVU_REGULAR = path.join(FONTS_DIR, "DejaVuSans.ttf")
const DEJAVU_BOLD = path.join(FONTS_DIR, "DejaVuSans-Bold.ttf")

/**
 * Strip control characters and clip to a max length.
 * Used to keep PDF Info dict + body strings safe against weird vendor inputs.
 */
function sanitizeText(input: string, maxLen = 200): string {
  return input.replace(/[\x00-\x1f\x7f]/g, "").slice(0, maxLen)
}

/**
 * Returns true when DejaVuSans TTFs are bundled and usable.
 */
export function unicodeFontsAvailable(): boolean {
  try {
    return fs.existsSync(DEJAVU_REGULAR) && fs.existsSync(DEJAVU_BOLD)
  } catch {
    return false
  }
}

const WINANSI_SAFE_RE = /^[\x00-\xff]*$/
/**
 * Returns true when every char in `s` falls within Latin-1 / WinAnsi range
 * (so Helvetica can render it without `?` substitution).
 */
export function isWinAnsiSafe(s: string): boolean {
  return WINANSI_SAFE_RE.test(s)
}

/**
 * Renders a JCA (Joint Controllership Agreement) as a real PDF Buffer.
 *
 * Returns a Promise<Buffer> whose first 5 bytes are the magic bytes `%PDF-`.
 * Buffer length is always > 1 KB for any non-empty vendorName/terms input.
 */
export async function renderJcaPdf({
  vendorName,
  terms,
  jcaId,
  generatedAt,
}: RenderJcaPdfOptions): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const safeVendorName = sanitizeText(vendorName, 200)
    const safeJcaId = sanitizeText(jcaId, 200)
    const safeGeneratedAt = sanitizeText(generatedAt, 64)

    const useUnicode = unicodeFontsAvailable()

    const doc = new PDFDocument({
      info: {
        // Non-PII metadata only — see review finding B-2.
        Title: `JCA-${safeVendorName}`,
        Author: "Grow Platform",
        Subject: "Joint Controllership Agreement",
        Creator: "Grow Platform v1.6.0",
        Keywords: `JCA ${safeJcaId}`,
      },
      margins: { top: 72, bottom: 72, left: 72, right: 72 },
    })

    const chunks: Buffer[] = []
    doc.on("data", (chunk: Buffer) => chunks.push(chunk))
    doc.on("end", () => resolve(Buffer.concat(chunks)))
    doc.on("error", reject)

    // Register Unicode fonts when available (covers Polish glyphs).
    const FONT_BODY = "body"
    const FONT_BODY_BOLD = "body-bold"
    if (useUnicode) {
      doc.registerFont(FONT_BODY, DEJAVU_REGULAR)
      doc.registerFont(FONT_BODY_BOLD, DEJAVU_BOLD)
    }
    const fontRegular = useUnicode ? FONT_BODY : "Helvetica"
    const fontBold = useUnicode ? FONT_BODY_BOLD : "Helvetica-Bold"

    // ── Title ──────────────────────────────────────────────────────────────
    doc
      .fontSize(18)
      .font(fontBold)
      .text("JOINT CONTROLLERSHIP AGREEMENT", { align: "center" })

    doc.moveDown(0.5)
    doc
      .fontSize(11)
      .font(fontRegular)
      .text(`JCA ID: ${safeJcaId}`, { align: "center" })
      .text(`Generated: ${safeGeneratedAt}`, { align: "center" })

    doc.moveDown(1)

    // ── Vendor block ───────────────────────────────────────────────────────
    doc.fontSize(13).font(fontBold).text("Vendor / Data Processor")
    doc.moveDown(0.3)
    doc.fontSize(11).font(fontRegular).text(`Name: ${safeVendorName}`)

    doc.moveDown(1)

    // ── Terms body ─────────────────────────────────────────────────────────
    doc.fontSize(13).font(fontBold).text("Terms and Conditions")
    doc.moveDown(0.5)
    doc
      .fontSize(10)
      .font(fontRegular)
      .text(terms, { align: "justify", lineGap: 2 })

    doc.moveDown(2)

    // ── Signature block ────────────────────────────────────────────────────
    doc.fontSize(11).font(fontBold).text("Signatures")
    doc.moveDown(0.5)
    doc
      .font(fontRegular)
      .fontSize(10)
      .text(
        "Controller representative: ______________________________   Date: ____________",
      )
    doc.moveDown(0.5)
    doc.text(
      "Vendor representative:      ______________________________   Date: ____________",
    )

    doc.end()
  })
}

/**
 * Returns the file extension for the rendered output.
 * v1.6.0+: always ".pdf"
 */
export function getRendererExtension(): string {
  return ".pdf"
}

/**
 * Returns the MIME type for the rendered output.
 * v1.6.0+: always "application/pdf"
 */
export function getRendererMimeType(): string {
  return "application/pdf"
}
