/**
 * Review 1-4-F1 / 1-4-F2 (v1.14.0) — regresja zapisu `metadata.gp.content_bar`
 * w `gp-config-sync-i18n-content.ts`.
 *
 * Pochodzenie defektu: Story 4.2 (materializacja content_bar). Story 1.4 jest
 * jego pierwszym konsumentem — backfill AC6 padał na gałęzi `seller` z
 * `MedusaError: Seller with id "" not found` (evidence
 * `1-4-sync-i18n-failure.log`), bo pętla persystencji wołała auto-generowaną
 * metodę MedusaService konwencją `(id, data)` ręcznie pisanego core'owego
 * ProductModuleService. Auto-generowane `update*` przyjmuje JEDEN argument
 * danych (obiekt `{id,...}`, tablicę albo `{selector, data}`) — pozycyjny
 * string nie jest tam id i schodzi jako pusty selektor.
 *
 * Test-the-test: mock `updateSellers` odtwarza wiernie semantykę
 * `medusa-internal-service.ts` (`AbstractService_.update`); na kodzie sprzed
 * fixu pierwszy test padał dokładnie komunikatem z live-runu
 * (zweryfikowane przebiegiem red → fix → green).
 */
import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"

import {
  applyContentBarMetadata,
  syncI18nTranslationContent,
} from "../gp-config-sync-i18n-content"

const MARKET_ID = "bonbeauty"

const LONG_BODY = Array.from({ length: 45 }, (_, i) => `slowo${i}`).join(" ")

/** Realny natywny opis PL produktu (≥80 słów — próg baru produktu). */
const REAL_PL_PRODUCT_BODY = Array.from({ length: 100 }, (_, i) => `opis${i}`).join(" ")

/** Stub tłumaczeniowy z source YAML (10-14 słów — jak w live-run 1-4-c2). */
const STUB_PL_BODY = Array.from({ length: 12 }, (_, i) => `stub${i}`).join(" ")

/**
 * Wierne odtworzenie semantyki auto-generowanego `MedusaService.update`:
 * jeden argument danych; wpis bez `id` (albo string pozycyjny zamiast obiektu)
 * kończy się `<Entity> with id "" not found` — dokładnie jak w
 * `@medusajs/utils/src/modules-sdk/medusa-internal-service.ts:409`.
 */
function makeAutoGeneratedUpdateMock(entityLabel: string, knownIds: Set<string>, store: Map<string, any>) {
  return jest.fn(async (input: unknown) => {
    const entries = Array.isArray(input) ? input : [input]
    for (const entry of entries) {
      const id =
        entry && typeof entry === "object" && typeof (entry as any).id === "string"
          ? (entry as any).id
          : ""
      if (!knownIds.has(id)) {
        throw new Error(`${entityLabel} with id "${id}" not found`)
      }
      store.set(id, (entry as any).metadata)
    }
    return entries
  })
}

function makeTranslationServiceMock() {
  return {
    listTranslations: jest.fn(async () => []),
    createTranslations: jest.fn(async (payloads: unknown[]) => payloads),
    updateTranslations: jest.fn(async (payloads: unknown[]) => payloads),
  }
}

describe("gp-config-sync-i18n-content — persystencja content_bar (review 1-4-F1/F2)", () => {
  let i18nDir: string

  beforeEach(async () => {
    i18nDir = await fs.mkdtemp(path.join(os.tmpdir(), "gp-sync-i18n-"))
  })

  afterEach(async () => {
    await fs.rm(i18nDir, { recursive: true, force: true })
  })

  it("F1: zapis gałęzi seller idzie konwencją MedusaService (jeden argument danych), nie (id, data)", async () => {
    await fs.writeFile(
      path.join(i18nDir, "sellers.yaml"),
      [
        "entries:",
        "  - handle: salon-anna",
        "    fields:",
        "      name:",
        '        uk-UA: "Салон Анна"',
        "      description:",
        `        pl-PL: "${STUB_PL_BODY}"`,
        `        uk-UA: "${LONG_BODY}"`,
        "",
      ].join("\n"),
      "utf8"
    )

    // Fix 1-4-c2: natywny PL sellera żyje na encji w DB (`description`),
    // stub pl-PL z YAML wyżej NIE może liczyć się do baru.
    const sellerStore = new Map<string, any>()
    const sellerModuleService = {
      list: jest.fn(async () => [
        {
          id: "sel_1",
          handle: "salon-anna",
          description: LONG_BODY,
          metadata: { gp: { market_id: MARKET_ID } },
        },
      ]),
      updateSellers: makeAutoGeneratedUpdateMock("Seller", new Set(["sel_1"]), sellerStore),
    }
    const productModuleService = {
      listProductCategories: jest.fn(async () => []),
      listProducts: jest.fn(async () => []),
    }

    // Na kodzie sprzed fixu: reject `Seller with id "" not found` (live repro).
    const summary = await syncI18nTranslationContent(
      makeTranslationServiceMock(),
      productModuleService,
      sellerModuleService,
      { i18nDir, locales: ["uk-UA"], marketId: MARKET_ID }
    )

    expect(sellerModuleService.updateSellers).toHaveBeenCalledTimes(1)
    const persisted = sellerStore.get("sel_1")
    expect(persisted?.gp?.content_bar?.pl).toEqual({ words: 45, bar: true })
    expect(persisted?.gp?.content_bar?.ua).toEqual({ words: 45, bar: true })
    expect(summary.entities.seller.content_bar_updated).toBe(1)
    expect(summary.entities.seller.content_bar_write_failed).toBe(0)
    expect(
      summary.warnings.filter((warning) => warning.includes("content_bar write"))
    ).toEqual([])
  })

  it("F2: jeden nieudany zapis NIE zabija przebiegu — warning z typem i handle, liczniki i summary przeżywają", async () => {
    const failures: string[] = []
    const productStore = new Map<string, any>()
    const productModuleService = {
      updateProducts: jest.fn(async (id: string, data: any) => {
        if (id === "prod_bad") {
          throw new Error('Product with id "prod_bad" not found')
        }
        productStore.set(id, data.metadata)
      }),
    }

    // `applyContentBarMetadata` sam inkrementuje `content_bar_updated` per
    // zmieniony target — liczniki startują od zera.
    const summaries = {
      product_category: emptySummary(),
      product: emptySummary(),
      seller: emptySummary(),
    }

    await expect(
      applyContentBarMetadata(
        { productModuleService, sellerModuleService: {} },
        [
          target("product", "prod_bad", "produkt-zly"),
          target("product", "prod_ok", "produkt-dobry"),
        ],
        { dryRun: false, summaries, warnings: failures }
      )
    ).resolves.toBeUndefined()

    // Drugi zapis wykonany mimo porażki pierwszego (per-encja fail-loud).
    expect(productStore.has("prod_ok")).toBe(true)
    // Nieudany zapis cofa inkrement `content_bar_updated` i liczy się osobno.
    expect(summaries.product.content_bar_updated).toBe(1)
    expect(summaries.product.content_bar_write_failed).toBe(1)
    // Warning niesie typ encji, handle i id — bez tego diagnoza = cały przebieg.
    expect(failures.some((w) => w.includes("product") && w.includes("produkt-zly") && w.includes("prod_bad"))).toBe(true)
  })

  it("F1 rec. 2: pusty entity id jest wykrywany PRZED ORM-em, z handle w warningu", async () => {
    const warnings: string[] = []
    const updateSellers = jest.fn()
    const summaries = {
      product_category: emptySummary(),
      product: emptySummary(),
      seller: emptySummary(),
    }

    await applyContentBarMetadata(
      { productModuleService: {}, sellerModuleService: { updateSellers } },
      [target("seller", "", "salon-bez-id")],
      { dryRun: false, summaries, warnings }
    )

    expect(updateSellers).not.toHaveBeenCalled()
    expect(summaries.seller.content_bar_updated).toBe(0)
    expect(summaries.seller.content_bar_write_failed).toBe(1)
    expect(warnings.some((w) => w.includes("seller") && w.includes("salon-bez-id") && w.includes("empty entity id"))).toBe(true)
  })
})

/**
 * Review 1-4-c2 (cykl 2) — regresja zerowego katalogu: bar.pl produktów liczony
 * ze STUBÓW pl-PL w source translations YAML (10-14 słów) zamiast z realnego
 * natywnego opisu PL z DB (80-112+ słów) → `content_bar.pl.bar=false` dla
 * 113/113 produktów bonbeauty i smoke 452/452 = 404_gate_description,
 * włącznie z /pl (evidence `1-4-smoke-pdp-locales.json`).
 *
 * Test-the-test: na kodzie sprzed fixu pierwszy test daje pl={words:12,
 * bar:false} (bar liczony ze stubu YAML) — red → fix → green.
 */
describe("gp-config-sync-i18n-content — bar.pl z realnego PL body (review 1-4-c2)", () => {
  let i18nDir: string

  beforeEach(async () => {
    i18nDir = await fs.mkdtemp(path.join(os.tmpdir(), "gp-sync-i18n-c2-"))
  })

  afterEach(async () => {
    await fs.rm(i18nDir, { recursive: true, force: true })
  })

  function makeProductServices(productDescription: unknown) {
    const productStore = new Map<string, any>()
    const productModuleService = {
      listProductCategories: jest.fn(async () => []),
      listProducts: jest.fn(async () => [
        {
          id: "prod_1",
          handle: "krem-regenerujacy",
          description: productDescription,
          metadata: { gp: { market_id: MARKET_ID } },
        },
      ]),
      updateProducts: jest.fn(async (id: string, data: any) => {
        productStore.set(id, data.metadata)
      }),
    }
    return { productModuleService, productStore }
  }

  async function writeProductsYaml() {
    await fs.writeFile(
      path.join(i18nDir, "products.yaml"),
      [
        "entries:",
        "  - handle: krem-regenerujacy",
        "    fields:",
        "      title:",
        '        uk-UA: "Крем регенеруючий"',
        "      description:",
        `        pl-PL: "${STUB_PL_BODY}"`,
        `        uk-UA: "${LONG_BODY}"`,
        "",
      ].join("\n"),
      "utf8"
    )
  }

  it("1-4-c2: bar.pl produktu liczy się z realnego opisu PL z DB (100 słów → bar=true), NIE ze stubu YAML", async () => {
    await writeProductsYaml()
    const { productModuleService, productStore } = makeProductServices(REAL_PL_PRODUCT_BODY)

    const summary = await syncI18nTranslationContent(
      makeTranslationServiceMock(),
      productModuleService,
      { list: jest.fn(async () => []) },
      { i18nDir, locales: ["uk-UA"], marketId: MARKET_ID }
    )

    const persisted = productStore.get("prod_1")
    // Realny PL (100 słów ≥ próg 80) wygrywa; stub YAML (12 słów) NIE liczy się.
    expect(persisted?.gp?.content_bar?.pl).toEqual({ words: 100, bar: true })
    // Locale tłumaczone nadal z ciała tłumaczenia w source YAML (45 < 80).
    expect(persisted?.gp?.content_bar?.ua).toEqual({ words: 45, bar: false })
    expect(summary.entities.product.content_bar_write_failed).toBe(0)
  })

  it("1-4-c2: brak opisu PL w DB → bar.pl jawnie {words:0, bar:false}, stub YAML nadal ignorowany", async () => {
    await writeProductsYaml()
    const { productModuleService, productStore } = makeProductServices(undefined)

    await syncI18nTranslationContent(
      makeTranslationServiceMock(),
      productModuleService,
      { list: jest.fn(async () => []) },
      { i18nDir, locales: ["uk-UA"], marketId: MARKET_ID }
    )

    expect(productStore.get("prod_1")?.gp?.content_bar?.pl).toEqual({ words: 0, bar: false })
  })
})

/**
 * Review 4-6-H1 — PL sellera pochodzi z `metadata.gp.description`, nie z kolumny.
 *
 * Test-the-test: na kodzie sprzed fixu (`match.description`) pierwszy przypadek
 * daje `pl = {words: 0, bar: false}`, bo `gp-config-sync-vendors` nigdy nie
 * zapisuje kolumny `seller.description` — opis z `market.yaml → vendors[]`
 * ląduje wyłącznie w `metadata.gp.description`. Dokładnie ten stan zastałem na
 * bazie dev: 3/3 sellerów z `content_bar.pl.words = 0`.
 */
describe("gp-config-sync-i18n-content — bar.pl sellera z metadata.gp.description (review 4-6-H1)", () => {
  let i18nDir: string

  beforeEach(async () => {
    i18nDir = await fs.mkdtemp(path.join(os.tmpdir(), "gp-sync-i18n-h1-"))
    await fs.writeFile(
      path.join(i18nDir, "sellers.yaml"),
      [
        "entries:",
        "  - handle: studio-nova",
        "    fields:",
        "      name:",
        '        uk-UA: "Studio Nova"',
        "      description:",
        `        pl-PL: "${STUB_PL_BODY}"`,
        `        uk-UA: "${LONG_BODY}"`,
        "",
      ].join("\n"),
      "utf8"
    )
  })

  afterEach(async () => {
    await fs.rm(i18nDir, { recursive: true, force: true })
  })

  async function runWithSeller(seller: Record<string, unknown>) {
    const store = new Map<string, any>()
    const sellerModuleService = {
      list: jest.fn(async () => [seller]),
      updateSellers: makeAutoGeneratedUpdateMock("Seller", new Set(["sel_1"]), store),
    }
    await syncI18nTranslationContent(
      makeTranslationServiceMock(),
      { listProductCategories: jest.fn(async () => []), listProducts: jest.fn(async () => []) },
      sellerModuleService,
      { i18nDir, locales: ["uk-UA"], marketId: MARKET_ID }
    )
    return store.get("sel_1")
  }

  it("kolumna PUSTA, opis w metadata.gp.description → bar.pl liczy się z metadanych", async () => {
    const persisted = await runWithSeller({
      id: "sel_1",
      handle: "studio-nova",
      description: null,
      metadata: { gp: { market_id: MARKET_ID, description: LONG_BODY } },
    })
    expect(persisted?.gp?.content_bar?.pl).toEqual({ words: 45, bar: true })
  })

  it("brak opisu po obu stronach → bar.pl jawnie {words:0, bar:false}, stub YAML nadal ignorowany", async () => {
    const persisted = await runWithSeller({
      id: "sel_1",
      handle: "studio-nova",
      description: null,
      metadata: { gp: { market_id: MARKET_ID } },
    })
    expect(persisted?.gp?.content_bar?.pl).toEqual({ words: 0, bar: false })
  })

  it("legacy: opis tylko w kolumnie nadal działa (fallback nie zniknął)", async () => {
    const persisted = await runWithSeller({
      id: "sel_1",
      handle: "studio-nova",
      description: LONG_BODY,
      metadata: { gp: { market_id: MARKET_ID } },
    })
    expect(persisted?.gp?.content_bar?.pl).toEqual({ words: 45, bar: true })
  })

  it("kolumna WYGRYWA z lustrem — bar mierzy treść, którą widzi storefront", async () => {
    // Review cykl 4 (RED-FIRST): przy kolejności `lustro → kolumna` bar liczył
    // STARY seed z `metadata.gp.description`, mimo że API i storefront czytają
    // kolumnę. Po edycji opisu przez vendora metryka opisywała treść, której
    // nikt już nie widzi.
    const persisted = await runWithSeller({
      id: "sel_1",
      handle: "studio-nova",
      description: LONG_BODY,
      metadata: { gp: { market_id: MARKET_ID, description: STUB_PL_BODY } },
    })
    expect(persisted?.gp?.content_bar?.pl).toEqual({ words: 45, bar: true })
  })
})

function emptySummary() {
  return {
    source_entries: 0,
    resolved_entries: 0,
    translation_records: 0,
    created: 0,
    updated: 0,
    unchanged: 0,
    skipped: 0,
    missing_handles: [] as string[],
    content_bar_updated: 0,
    content_bar_unchanged: 0,
    content_bar_write_failed: 0,
    unshipped_records: 0,
  }
}

function target(entityType: "product" | "product_category" | "seller", entityId: string, handle: string) {
  return {
    entityType,
    entityId,
    handle,
    metadata: { gp: { market_id: MARKET_ID } },
    bodiesByLocale: { "pl-PL": LONG_BODY },
  }
}
